/*
    Використання блоку finally має свої переваги в деяких ситуаціях. 
    Блок finally завжди викликається, незалежно від того, чи виникла помилка,
    чи ні, і це дозволяє здійснити очищення ресурсів або виконати інші завершальні
    дії навіть у разі виникнення виключення.

    Наприклад, у може бути ситуація, коли потрібно завершити певний процес або
    виконати певні кроки навіть у разі виникнення помилки. Приклад:
*/

let file;
try {
  file = openFile('file.txt');
} catch (error) {
  console.log('Помилка: ', error.message);
} finally {
  if (file) {
    file.close();
  }
}

/*
    У цьому прикладі, навіть якщо виникне помилка при відкриванні файлу, 
    блок finally гарантує, що файл буде закритий перед тим, як програма завершить свою роботу.

    Загально кажучи, використання блоку finally рекомендується там, де необхідно гарантувати
    виконання певних завершальних дій незалежно від того, чи виникає помилка.
*/